// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	home "github.com/congim/mall/apps/app/api/internal/handler/home"
	"github.com/congim/mall/apps/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/banner",
				Handler: home.HomeBannerHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/home"),
	)
}
