// Code generated by goctl. DO NOT EDIT.
package types

type BannerRes struct {
	Banners []*Banner `json:"banners"`
}

type Banner struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Image string `json:"image"`
	Url   string `json:"url"`
}
