// Code generated by goctl. DO NOT EDIT!
// Source: home.proto

package server

import (
	"context"

	"github.com/congim/mall/apps/home/rpc/home"
	"github.com/congim/mall/apps/home/rpc/internal/logic"
	"github.com/congim/mall/apps/home/rpc/internal/svc"
)

type HomeServer struct {
	svcCtx *svc.ServiceContext
	home.UnimplementedHomeServer
}

func NewHomeServer(svcCtx *svc.ServiceContext) *HomeServer {
	return &HomeServer{
		svcCtx: svcCtx,
	}
}

func (s *HomeServer) Banner(ctx context.Context, in *home.BannerReq) (*home.BannerRes, error) {
	l := logic.NewBannerLogic(ctx, s.svcCtx)
	return l.Banner(in)
}
