// Code generated by goctl. DO NOT EDIT!
// Source: banner.proto

package banner

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Banner interface {
		HomeBanner(ctx context.Context, in *BannerReq, opts ...grpc.CallOption) (*BannerRes, error)
	}

	defaultBanner struct {
		cli zrpc.Client
	}
)

func NewBanner(cli zrpc.Client) Banner {
	return &defaultBanner{
		cli: cli,
	}
}

func (m *defaultBanner) HomeBanner(ctx context.Context, in *BannerReq, opts ...grpc.CallOption) (*BannerRes, error) {
	client := NewBannerClient(m.cli.Conn())
	return client.HomeBanner(ctx, in, opts...)
}
