// Code generated by goctl. DO NOT EDIT!
// Source: home.proto

package home

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Home interface {
		Banner(ctx context.Context, in *BannerReq, opts ...grpc.CallOption) (*BannerRes, error)
	}

	defaultHome struct {
		cli zrpc.Client
	}
)

func NewHome(cli zrpc.Client) Home {
	return &defaultHome{
		cli: cli,
	}
}

func (m *defaultHome) Banner(ctx context.Context, in *BannerReq, opts ...grpc.CallOption) (*BannerRes, error) {
	client := NewHomeClient(m.cli.Conn())
	return client.Banner(ctx, in, opts...)
}
